trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  displayName: Download Public Key
  name: azure_rsa_public_key
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformTaskV3@3
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes/'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(azure_rsa_public_key.secureFilePath)'
    backendServiceArm: 'azure-service-principal-svc'
    backendAzureRmResourceGroupName: 'terraform_backend_rg'
    backendAzureRmStorageAccountName: 'terraformbackendstinkr5f'
    backendAzureRmContainerName: 'blob-container-1-origin-dev-eu'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV3@3
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes/'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(azure_rsa_public_key.secureFilePath)'
    environmentServiceNameAzureRM: 'azure-service-principal-svc'